# Generated by Django 5.2.6 on 2025-09-20 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('ronda_diaria', 'Ronda diaria'), ('servicio_salas', 'Servicio de salas'), ('laboratorio_clinico', 'Laboratorio clínico'), ('sedes_externas', 'Sedes externas')], max_length=32)),
                ('subservicio', models.CharField(max_length=100)),
                ('hallazgo', models.TextField(blank=True)),
                ('placa_equipo', models.CharField(blank=True, max_length=100)),
                ('orden_trabajo', models.CharField(blank=True, max_length=100)),
                ('eventos_seguridad', models.TextField(blank=True)),
                ('firma_servicio', models.CharField(max_length=100)),
                ('firma_ronda', models.CharField(max_length=100)),
                ('sin_novedad', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rondas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de ronda',
                'verbose_name_plural': 'Registros de rondas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SurgeryRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField(help_text='Fecha correspondiente al lunes de la semana registrada.')),
                ('datos', models.JSONField()),
                ('firma_servicio', models.CharField(max_length=100)),
                ('firma_ronda', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formatos_cirugia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ronda de cirugía',
                'verbose_name_plural': 'Rondas de cirugía',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
