# Generated by Django 5.2.6 on 2025-09-29 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rondas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('PRIORITARIO', 'Prioritario'), ('DIARIA', 'Ronda diaria'), ('SALAS', 'Servicio de salas'), ('LAB', 'Laboratorio clínico'), ('SEDES', 'Sedes externas')], max_length=20)),
                ('day_rules', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.AddField(
            model_name='roundentry',
            name='fuera_de_servicio',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='roundentry',
            name='nombre_encargado_ronda',
            field=models.CharField(default='Sin especificar', max_length=100),
        ),
        migrations.AddField(
            model_name='roundentry',
            name='nombre_encargado_servicio',
            field=models.CharField(default='Sin especificar', max_length=100),
        ),
        migrations.AlterField(
            model_name='roundentry',
            name='firma_ronda',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
        migrations.AlterField(
            model_name='roundentry',
            name='firma_servicio',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
        migrations.AlterField(
            model_name='surgeryround',
            name='firma_ronda',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
        migrations.AlterField(
            model_name='surgeryround',
            name='firma_servicio',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('room_type', models.CharField(choices=[('sala_cirugia', 'Sala de cirugía'), ('habitacion', 'Habitación'), ('consulta', 'Consulta'), ('laboratorio', 'Laboratorio'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rondas.service')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('plate_number', models.CharField(blank=True, max_length=100, verbose_name='Placa')),
                ('status', models.CharField(choices=[('operativo_completo', 'Operativo completo'), ('operativo_parcial', 'Operativo parcial'), ('fuera_de_servicio', 'Fuera de servicio')], default='operativo_completo', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='rondas.room')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='rondas.service')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
    ]
