# Generated by Django 5.2.6 on 2025-09-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rondas', '0004_roundentry_tiene_eventos_seguridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundentry',
            name='categoria',
            field=models.CharField(choices=[('prioritarios', 'Prioritarios'), ('ronda_diaria', 'Ronda diaria'), ('servicio_salas', 'Servicio de salas'), ('laboratorio_clinico', 'Laboratorio clínico'), ('sedes_externas', 'Sedes externas')], max_length=32),
        ),
        migrations.AlterField(
            model_name='roundentry',
            name='firma_ronda',
            field=models.TextField(blank=True, null=True, verbose_name='Firma del encargado de la ronda'),
        ),
        migrations.AlterField(
            model_name='roundentry',
            name='firma_servicio',
            field=models.TextField(blank=True, null=True, verbose_name='Firma del encargado del servicio'),
        ),
        migrations.AlterField(
            model_name='surgeryround',
            name='firma_ronda',
            field=models.TextField(blank=True, null=True, verbose_name='Firma del encargado de la ronda'),
        ),
        migrations.AlterField(
            model_name='surgeryround',
            name='firma_servicio',
            field=models.TextField(blank=True, null=True, verbose_name='Firma del encargado del servicio'),
        ),
    ]
